language: objective-c
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.0
sudo: false

cache:
  bundler: true
  cocoapods: true
  directories:
    - ~/.nvm
    - node_modules

env:
  - TEST_COMMAND=bin/test-js
  - TEST_COMMAND=bin/build-ios
  - TEST_COMMAND=bin/build-android

before_install:
  - export NVM_DIR=~/.nvm
  - which nvm || curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
  -  source ~/.nvm/nvm.sh --install
  - nvm install 5.5.0
  - bin/ci-install-environment
  - export ANDROID_HOME=/usr/local/opt/android-sdk
  - export TERM=dumb

install:
  - bin/setup

script:
  - npm test

after_script:
  - '[ "$TEST_COMMAND" = "bin/test-js" ] && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls || true'
