/**
 * This file is generated by running bin/export-design.
 *
 * @providesModule constants/colors
 */

module.exports = {
  "assistance": "#3B4851",
  "assistanceLight": "#5B6D7B",
  "blue": "#2B91FF",
  "blueLight": "#52ABF5",
  "dark": "#253240",
  "green": "#35DE81",
  "greenLight": "#7EE78B",
  "light": "#FFFFFF",
  "paletteBlue0": "#62D0CB",
  "paletteBlue1": "#3B99C9",
  "paletteBlue2": "#61708C",
  "paletteGreen0": "#71C643",
  "paletteGreen1": "#50BE3D",
  "paletteGreen2": "#17B373",
  "paletteOrange0": "#FFC438",
  "paletteOrange1": "#FCAF17",
  "paletteOrange2": "#B65B42",
  "paletteRed0": "#F6534A",
  "paletteRed1": "#F26D5F",
  "paletteRed2": "#C92841",
  "paletteViolet0": "#E36CED",
  "paletteViolet1": "#7945D0",
  "paletteViolet2": "#6C49A6",
  "paletteYellow0": "#FFCC02",
  "paletteYellow1": "#FFCC02",
  "paletteYellow2": "#E08C29",
  "red": "#FC3252",
  "redLight": "#FF5252",
  "violet": "#7838FE",
  "violetLight": "#B868FD",
  "yellow": "#D5A844",
  "yellowLight": "#E6AE46"
};
